apiVersion: batch/v1
kind: Job
metadata:
  name: job-wq-2
spec:
  parallelism: 5
  template:
    metadata:
      name: job-wq-2
    spec:
      containers:
      - name: job-pod
        image: smartbuddy/job-img:v3
        command: ["python","worker.py"]
        args: ["5"]
      restartPolicy: OnFailure
