---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-vol
  labels:
    app: nginx-vol
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 2Gi
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /home/ishaqshaikh/k8sdata
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-pvc-claim
  labels:
    app: nginx-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      app: "nginx-vol"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginx
  name: nginx
  namespace: operations
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx
        name: nginx
        env:
        - name: APP_NAME
          value: "Hello App!"
        volumeMounts:
        - name: nginx-storage
          mountPath: /data
      volumes:
      - name: nginx-storage
        persistentVolumeClaim:
          claimName: nginx-pvc-claim
