# ---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: pv-log
# spec:
#   storageClassName: manual  
#   accessModes:  
#   - ReadWriteMany
#   persistentVolumeReclaimPolicy: Retain  
#   capacity:    
#     storage: 100Mi
#   hostPath:    
#     path: /pv/log
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: claim-log-1
# spec:  
#   accessModes:
#     - ReadWriteMany  
#   resources:    
#     requests:
#       storage: 50Mi  
#   storageClassName: manual
#   volumeName: pv-log  
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: models-1-0-0
  labels:
    name: models-1-0-0
spec:
  capacity:
    storage: 10Gi
  storageClassName: standard
  accessModes:
    - ReadOnlyMany
  gcePersistentDisk:
    pdName: models-1-0-0
    fsType: ext4
    readOnly: true
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: models-1-0-0-claim
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 200Gi
  selector:
    matchLabels:
      name: models-1-0-0