---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-log
spec:
  storageClassName: manual  
  accessModes:  
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain  
  capacity:    
    storage: 100Mi
  hostPath:    
    path: /pv/log
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: claim-log-1
spec:  
  accessModes:
    - ReadWriteMany  
  resources:    
    requests:
      storage: 50Mi  
  storageClassName: manual
  volumeName: pv-log  
