---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: fs-del-rp-sc
provisioner: filestore.csi.storage.gke.io
# Underlying FS instance will delete 
reclaimPolicy: Delete
parameters:
  # Name of the VPC. Note that non-default VPCs require special firewall rules to be setup
  network: pilot-unbxd-main-vpc
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
