---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  namespace: task-ns
data:
  td-agent.conf: |
    <match fluent.info>
      @type null
    </match>
    <source>
      @type tail
      path /var/log/wordpress/access.log
      pos_file /var/log/td-agent/httpd-access.log.pos
      format multiline

      # format_firstline /\d{4}-\d{1,2}-\d{1,2}/
      # format1 /^(?<time>\d{4}-\d{1,2}-\d{1,2}\s+[^ ]*)\s+(?<level>[^ ]*)\s+[^ ]\s+---\s+\[(?<thread>.*?)\]\s+(?<message>.*)/
      read_from_head true
      tag apache.log
    </source>



    # <filter *.*>
    #   type record_transformer
    #   <record>
    #   #hostname ${hostname}
    #   namespace "#{ENV['MY_POD_NAMESPACE']}"
    #   podname "#{ENV['MY_POD_NAME']}"
    #   deploymentname "#{ENV['MY_DEPLOYMENT_NAME']}"
    #   </record>
    # </filter>

    <match *.*>
    @type elasticsearch
    # user elastic
    # password changeme
    include_tag_key true
    host elasticsearch.task-ns.svc.cluster.local
    port 9200
    #index_name "#{"application-log-"+Time.now().getutc.strftime("%d.%m.%Y")}"
    logstash_format true
    flush_interval 5s
    # Never wait longer than 5 minutes between retries.
    max_retry_wait 300
    # Disable the limit on the number of retries (retry forever).
    disable_retry_limit
    </match>


