apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: apache
  name: apache-deploy
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: apache
status:
  loadBalancer: {}
---
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: apache
  name: apache-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: apache
    spec:
      containers:
      - image: httpd
        name: apache-deploy
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 30m
            memory: 100Mi
        volumeMounts:
        - mountPath: /dev/
          name: log-storage
      - name: sidecar-log-collector
        image: smartbuddy/fluentd-agent:v1
        command: ["/bin/sh","-c"]
        args: ["/usr/sbin/td-agent"]
        env:
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                  fieldPath: metadata.name
          - name: MY_POD_NAMESPACE
            valueFrom:
              fieldRef:
                  fieldPath: metadata.namespace
        volumeMounts:
        - name: log-storage
          readOnly: true
          mountPath: /var/log/apache2/
        - name: fluentd-config
          mountPath: /etc/td-agent/
        # - name: podinfo
        #   mountPath: /etc/podinfo     
      volumes:
      - name: fluentd-config
        configMap:
          name: fluentd-config
      - name: log-storage
        emptyDir: {}
      # - name: podinfo
      #   downwardAPI:
      #     items:
      #     - path: "labels"
      #       fieldRef:
      #           fieldPath: metadata.labels
      # imagePullSecrets:
      #   - name: nexus-image-pull 
