apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: wordpress
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: wordpress
status:
  loadBalancer: {}
---
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: wordpress
  name: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      run: wordpress
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: wordpress
    spec:
      containers:
      - image: wordpress
        name: wordpress
        ports:
        - containerPort: 80
        env:
        - name: APACHE_LOG_DIR
          value: /var/log/wordpress
        resources:
          limits:
            cpu: 50m
            memory: 500Mi
          requests:
            cpu: 50m
            memory: 500Mi
        volumeMounts:
        - name: wp-data
          mountPath: /var/www/html
        - name: log-storage
          mountPath: /var/log/wordpress
          
      - name: sidecar-log-collector
        image: smartbuddy/fluentd-agent:v1
        command: ["/bin/sh","-c"]
        args: ["/usr/sbin/td-agent"]
        env:
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                  fieldPath: metadata.name
          - name: MY_POD_NAMESPACE
            valueFrom:
              fieldRef:
                  fieldPath: metadata.namespace
        volumeMounts:
        - name: log-storage
          # readOnly: true
          mountPath: /var/log/wordpress
        - name: fluentd-config
          mountPath: /etc/td-agent/
        # - name: podinfo
        #   mountPath: /etc/podinfo     
      volumes:
      - name: fluentd-config
        configMap:
          name: fluentd-config
      - name: log-storage
        emptyDir: {}
      - name: wp-data
        hostPath:
          path: /tmp/wp-data/


status: {}
