apiVersion: apps/v1beta2
kind: DaemonSet
metadata:
  name: ssd-monitor
spec:
  selector:
    matchLabels:
      app: ssd-monitor
  template:
    metadata:
      labels:
        app: ssd-monitor
    spec:
      nodeSelector:
        disk: ssd # selecting the node having labelled as disk=ssd
      containers:
      - args:
        - sleep
        - "3600"
        image: busybox
        name: main  # k get no -l disk
      #kubectl label node [node_name] disk=ssd
        #kubectl label node node_name disk-
